Globals:
  Function:
    Variables:
      TABLE_WISHLIST: 'your_table_name_here'

Resources:
  WishlistTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      BillingMode: 'PAY_PER_REQUEST'
      AttributeDefinitions:
        - AttributeName: 'code_client'
          AttributeType: 'S'
        - AttributeName: 'code_produit'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'code_client'
          KeyType: 'HASH'
        - AttributeName: 'code_produit'
          KeyType: 'RANGE'

Policies:
  DynamoPolicy:
    Resources: 
      - !GetAtt WishlistTable.Arn

HttpApi:
  CorsConfiguration:
    AllowMethods:
      - OPTIONS
      - GET
      - POST
      - DELETE

Functions:
  WishlistPutFunction:
    Handler: wishlist_put.handler
    CodeUri: src/functions/
    Policies:
      - !Ref DynamoPolicy
    Events:
      Api:
        Type: Api
        Properties:
          Path: /clients/me/wishlist
          Method: post
          ApiId: !Ref IabagHttpApi

  WishlistListMyWishlistFunction:
    Handler: wishlist_get_list.handler
    CodeUri: src/functions/
    Policies:
      - !Ref DynamoPolicy
    Events:
      Api:
        Type: Api
        Properties:
          Path: /clients/me/wishlist
          Method: get
          ApiId: !Ref IabagHttpApi

  WishlistDeleteFunction:
    Handler: wishlist_delete.handler
    CodeUri: src/functions/
    Policies:
      - !Ref DynamoPolicy
    Events:
      Api:
        Type: Api
        Properties:
          Path: /clients/me/wishlist/{code}
          Method: delete
          ApiId: !Ref IabagHttpApi